import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

import FilterByCategory from "../components/FilterByCategory";

import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import TrendingAnimes from "../components/TrendingAnimes";

export default function Home({ data, popularAnimes }: any) {
  return (
    <div className="relative h-full   bg-[#f5f5f5]  flex flex-row">
      <Head>
        <title>Anime Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sm:flex hidden p-4 relative">
        <Navbar />
      </div>
      <div className="flex flex-col w-full ">
        <Hero data={data} />
        <TrendingAnimes data={data} popularAnimes={popularAnimes} />
      </div>
      {/*  <FilterByCategory anime={data} />;*/}
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(`http://193.123.33.166/genres`);
  const data = await res.json();
  const res2 = await fetch(
    " http://193.123.33.166/genre-recommendation?startDate=2022-09-30&orderBy=members&status=airing&page=1&sort=desc"
  );
  const popularAnimes = await res2.json();
  return {
    props: { data, popularAnimes }, // will be passed to the page component as props
  };
}
