import Head from "next/head";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import TrendingAnimes from "../components/TrendingAnimes";
import fetcher from "../lib/fetcher";
import AnimeLikeBtn from "../components/AnimeLikeBtn";
import { useEffect, useRef, useState } from "react";
import Confetti from "react-confetti";

export default function Home({ fallbackPopularAnimes }: any) {
  const [party, setParty] = useState(false);
  const keyArray: string[] = [];
  useEffect(() => {
    const detectKeyDown = (e: any) => {
      keyArray.push(e.key);
      if (keyArray.length > 11) {
        keyArray.shift();
      }
      if (keyArray.join("") === "zigidigidum") {
        setParty(true);
      }
      console.log(keyArray.join(""));
    };
    document.addEventListener("keydown", detectKeyDown);
  }, []);

  return (
    <>
      <Layout>
        <Head>
          <title>Anime Recommender</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {party && <Confetti width={1900} height={1080} />}

        <Hero />
        <TrendingAnimes fallbackPopularAnimes={fallbackPopularAnimes} />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const fallbackPopularAnimes = await fetcher(
    `${process.env.ANIME_BASE_URL}/top/anime?filter=airing&page=1`
  );

  return {
    props: { fallbackPopularAnimes }, // will be passed to the page component as props
  };
}
