import Head from "next/head";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import TrendingAnimes from "../components/TrendingAnimes";
import fetcher from "../lib/fetcher";
import AnimeLikeBtn from "../components/AnimeLikeBtn";

export default function Home({ fallbackPopularAnimes }: any) {
  return (
    <>
      <Layout>
        <Head>
          <title>Anime Recommender</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero />
        <TrendingAnimes fallbackPopularAnimes={fallbackPopularAnimes} />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const fallbackPopularAnimes = await fetcher(
    `${process.env.ANIME_BASE_URL}/top/anime?filter=airing&page=1`
  );

  return {
    props: { fallbackPopularAnimes }, // will be passed to the page component as props
  };
}
